// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoRCG7lNjaHrAFJY4D5rzha_hgTUO7dPA',
    appId: '1:784046577885:web:cd3448dacbbe4c1a9be334',
    messagingSenderId: '784046577885',
    projectId: 'plant-b57c7',
    authDomain: 'plant-b57c7.firebaseapp.com',
    databaseURL: 'https://plant-b57c7-default-rtdb.firebaseio.com',
    storageBucket: 'plant-b57c7.appspot.com',
    measurementId: 'G-6RSLDMRYB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTT3JwJWaodZvdPrhmqCwAC45WQTmsXCU',
    appId: '1:784046577885:android:5119299bc2d662c19be334',
    messagingSenderId: '784046577885',
    projectId: 'plant-b57c7',
    databaseURL: 'https://plant-b57c7-default-rtdb.firebaseio.com',
    storageBucket: 'plant-b57c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1bM6xPzt0tDOTxTKXMDsGp4i6XdhWpOo',
    appId: '1:784046577885:ios:a9bd4aa5b3603e129be334',
    messagingSenderId: '784046577885',
    projectId: 'plant-b57c7',
    databaseURL: 'https://plant-b57c7-default-rtdb.firebaseio.com',
    storageBucket: 'plant-b57c7.appspot.com',
    iosBundleId: 'com.example.plantsmart30',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1bM6xPzt0tDOTxTKXMDsGp4i6XdhWpOo',
    appId: '1:784046577885:ios:898843a8b14eac3b9be334',
    messagingSenderId: '784046577885',
    projectId: 'plant-b57c7',
    databaseURL: 'https://plant-b57c7-default-rtdb.firebaseio.com',
    storageBucket: 'plant-b57c7.appspot.com',
    iosBundleId: 'com.example.plantsmart30.RunnerTests',
  );
}
